// Данные автомобилей с уникальными изображениями
const carsData = [
    {
        id: 1,
        brand: 'BMW',
        model: '3 Series',
        year: 2022,
        price: 3500000,
        mileage: 15000,
        bodyType: 'седан',
        engine: '2.0 л, 184 л.с.',
        transmission: 'Автомат',
        drive: 'Задний',
        color: 'Черный',
        description: 'Отличное состояние, один владелец, полная комплектация, сервисная книжка.',
        imageUrl: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&h=600&fit=crop&auto=format'
    },
    {
        id: 2,
        brand: 'Mercedes-Benz',
        model: 'C-Class',
        year: 2021,
        price: 3200000,
        mileage: 25000,
        bodyType: 'седан',
        engine: '1.6 л, 156 л.с.',
        transmission: 'Автомат',
        drive: 'Задний',
        color: 'Белый',
        description: 'Премиум комплектация, все опции, идеальное состояние.',
        imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&h=600&fit=crop&auto=format'
    },
    {
        id: 3,
        brand: 'Audi',
        model: 'RS 6 Avant',
        year: 2023,
        price: 8500000,
        mileage: 5000,
        bodyType: 'универсал',
        engine: '4.0 л, 600 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Черный',
        description: 'Мощный спортивный универсал, новый автомобиль, гарантия.',
        imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&auto=format'
    },
    {
        id: 4,
        brand: 'Toyota',
        model: 'Camry',
        year: 2022,
        price: 2800000,
        mileage: 20000,
        bodyType: 'седан',
        engine: '2.5 л, 181 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Серебристый',
        description: 'Надежный японский седан, отличное состояние.',
        imageUrl: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&h=600&fit=crop&auto=format'
    },
    {
        id: 5,
        brand: 'Volkswagen',
        model: 'Golf',
        year: 2021,
        price: 1800000,
        mileage: 30000,
        bodyType: 'хэтчбек',
        engine: '1.4 л, 150 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Синий',
        description: 'Компактный и экономичный хэтчбек.',
        imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop&auto=format'
    },
    {
        id: 6,
        brand: 'BMW',
        model: 'X5',
        year: 2022,
        price: 5500000,
        mileage: 12000,
        bodyType: 'внедорожник',
        engine: '3.0 л, 340 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Черный',
        description: 'Премиум внедорожник, все опции, идеальное состояние.',
        imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop&auto=format'
    },
    {
        id: 7,
        brand: 'Mercedes-Benz',
        model: 'GLE',
        year: 2021,
        price: 5200000,
        mileage: 18000,
        bodyType: 'внедорожник',
        engine: '2.0 л, 258 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Белый',
        description: 'Комфортный и просторный внедорожник.',
        imageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&h=600&fit=crop&auto=format'
    },
    {
        id: 8,
        brand: 'Audi',
        model: 'Q5',
        year: 2023,
        price: 4500000,
        mileage: 5000,
        bodyType: 'внедорожник',
        engine: '2.0 л, 249 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Серый',
        description: 'Новый кроссовер, гарантия дилера.',
        imageUrl: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&h=600&fit=crop&auto=format'
    },
    {
        id: 9,
        brand: 'Toyota',
        model: 'RAV4',
        year: 2022,
        price: 3200000,
        mileage: 22000,
        bodyType: 'внедорожник',
        engine: '2.5 л, 203 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Белый',
        description: 'Надежный японский кроссовер.',
        imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=600&fit=crop&auto=format'
    },
    {
        id: 10,
        brand: 'Volkswagen',
        model: 'Tiguan',
        year: 2021,
        price: 2500000,
        mileage: 35000,
        bodyType: 'внедорожник',
        engine: '2.0 л, 180 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Серебристый',
        description: 'Популярный немецкий кроссовер.',
        imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&auto=format'
    },
    {
        id: 11,
        brand: 'BMW',
        model: '1 Series',
        year: 2020,
        price: 2200000,
        mileage: 40000,
        bodyType: 'хэтчбек',
        engine: '1.5 л, 140 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Красный',
        description: 'Компактный премиум хэтчбек.',
        imageUrl: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=800&h=600&fit=crop&auto=format'
    },
    {
        id: 12,
        brand: 'Mercedes-Benz',
        model: 'A-Class',
        year: 2022,
        price: 2800000,
        mileage: 15000,
        bodyType: 'хэтчбек',
        engine: '1.3 л, 163 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Черный',
        description: 'Стильный компактный Mercedes.',
        imageUrl: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&h=600&fit=crop&auto=format'
    },
    {
        id: 13,
        brand: 'Audi',
        model: 'A3',
        year: 2021,
        price: 2400000,
        mileage: 28000,
        bodyType: 'хэтчбек',
        engine: '1.4 л, 150 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Белый',
        description: 'Спортивный компактный Audi.',
        imageUrl: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&h=600&fit=crop&auto=format'
    },
    {
        id: 14,
        brand: 'Toyota',
        model: 'Corolla',
        year: 2022,
        price: 1900000,
        mileage: 20000,
        bodyType: 'седан',
        engine: '1.8 л, 140 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Серый',
        description: 'Надежный и экономичный седан.',
        imageUrl: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=700&h=500&fit=crop&auto=format'
    },
    {
        id: 15,
        brand: 'Volkswagen',
        model: 'Passat',
        year: 2021,
        price: 2100000,
        mileage: 32000,
        bodyType: 'седан',
        engine: '1.8 л, 180 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Черный',
        description: 'Комфортный бизнес-седан.',
        imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=700&h=500&fit=crop&auto=format'
    },
    {
        id: 16,
        brand: 'BMW',
        model: '5 Series',
        year: 2022,
        price: 4800000,
        mileage: 10000,
        bodyType: 'седан',
        engine: '2.0 л, 252 л.с.',
        transmission: 'Автомат',
        drive: 'Задний',
        color: 'Синий',
        description: 'Премиум бизнес-седан, полная комплектация.',
        imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=700&h=500&fit=crop&auto=format'
    },
    {
        id: 17,
        brand: 'Mercedes-Benz',
        model: 'E-Class',
        year: 2021,
        price: 4500000,
        mileage: 20000,
        bodyType: 'седан',
        engine: '2.0 л, 258 л.с.',
        transmission: 'Автомат',
        drive: 'Задний',
        color: 'Серебристый',
        description: 'Роскошный бизнес-седан.',
        imageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=700&h=500&fit=crop&auto=format'
    },
    {
        id: 18,
        brand: 'Audi',
        model: 'A6',
        year: 2023,
        price: 5000000,
        mileage: 3000,
        bodyType: 'седан',
        engine: '2.0 л, 245 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Черный',
        description: 'Новый премиум седан, гарантия.',
        imageUrl: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=700&h=500&fit=crop&auto=format'
    },
    {
        id: 19,
        brand: 'Toyota',
        model: 'Highlander',
        year: 2022,
        price: 4200000,
        mileage: 15000,
        bodyType: 'внедорожник',
        engine: '3.5 л, 295 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Белый',
        description: 'Просторный семиместный внедорожник.',
        imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=700&h=500&fit=crop&auto=format'
    },
    {
        id: 20,
        brand: 'Volkswagen',
        model: 'Touareg',
        year: 2021,
        price: 4800000,
        mileage: 25000,
        bodyType: 'внедорожник',
        engine: '3.0 л, 340 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Коричневый',
        description: 'Премиум внедорожник, все опции.',
        imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=700&h=500&fit=crop&auto=format'
    },
    {
        id: 21,
        brand: 'BMW',
        model: 'X3',
        year: 2022,
        price: 4200000,
        mileage: 18000,
        bodyType: 'внедорожник',
        engine: '2.0 л, 184 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Серый',
        description: 'Компактный премиум внедорожник.',
        imageUrl: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=700&h=500&fit=crop&auto=format'
    },
    {
        id: 22,
        brand: 'Mercedes-Benz',
        model: 'GLC',
        year: 2023,
        price: 4400000,
        mileage: 6000,
        bodyType: 'внедорожник',
        engine: '2.0 л, 258 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Синий',
        description: 'Новый кроссовер, гарантия.',
        imageUrl: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=700&h=500&fit=crop&auto=format'
    },
    {
        id: 23,
        brand: 'Audi',
        model: 'A5',
        year: 2022,
        price: 3600000,
        mileage: 12000,
        bodyType: 'купе',
        engine: '2.0 л, 190 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Красный',
        description: 'Стильное спортивное купе.',
        imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=700&h=500&fit=crop&auto=format'
    },
    {
        id: 24,
        brand: 'BMW',
        model: '4 Series',
        year: 2021,
        price: 3800000,
        mileage: 22000,
        bodyType: 'купе',
        engine: '2.0 л, 184 л.с.',
        transmission: 'Автомат',
        drive: 'Задний',
        color: 'Синий',
        description: 'Спортивное купе, отличное состояние.',
        imageUrl: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=900&h=600&fit=crop&auto=format'
    },
    {
        id: 25,
        brand: 'Mercedes-Benz',
        model: 'C-Class Coupe',
        year: 2022,
        price: 3500000,
        mileage: 14000,
        bodyType: 'купе',
        engine: '1.6 л, 156 л.с.',
        transmission: 'Автомат',
        drive: 'Задний',
        color: 'Черный',
        description: 'Элегантное купе Mercedes.',
        imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=900&h=600&fit=crop&auto=format'
    },
    {
        id: 26,
        brand: 'Volkswagen',
        model: 'Jetta',
        year: 2021,
        price: 1600000,
        mileage: 38000,
        bodyType: 'седан',
        engine: '1.4 л, 150 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Белый',
        description: 'Экономичный компактный седан.',
        imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=900&h=600&fit=crop&auto=format'
    },
    {
        id: 27,
        brand: 'Toyota',
        model: 'Prius',
        year: 2022,
        price: 2400000,
        mileage: 18000,
        bodyType: 'хэтчбек',
        engine: '1.8 л, 122 л.с. (гибрид)',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Белый',
        description: 'Экономичный гибридный автомобиль.',
        imageUrl: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=900&h=600&fit=crop&auto=format'
    },
    {
        id: 28,
        brand: 'Audi',
        model: 'Q7',
        year: 2021,
        price: 5800000,
        mileage: 20000,
        bodyType: 'внедорожник',
        engine: '3.0 л, 340 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Черный',
        description: 'Просторный премиум внедорожник.',
        imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&h=600&fit=crop&auto=format'
    },
    {
        id: 29,
        brand: 'BMW',
        model: 'X1',
        year: 2022,
        price: 3200000,
        mileage: 16000,
        bodyType: 'внедорожник',
        engine: '2.0 л, 192 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Белый',
        description: 'Компактный кроссовер BMW.',
        imageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=900&h=600&fit=crop&auto=format'
    },
    {
        id: 30,
        brand: 'Mercedes-Benz',
        model: 'GLA',
        year: 2023,
        price: 3400000,
        mileage: 4000,
        bodyType: 'внедорожник',
        engine: '1.3 л, 163 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Серый',
        description: 'Новый компактный кроссовер.',
        imageUrl: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=900&h=600&fit=crop&auto=format'
    },
    {
        id: 31,
        brand: 'Lexus',
        model: 'RX',
        year: 2022,
        price: 4800000,
        mileage: 18000,
        bodyType: 'внедорожник',
        engine: '3.5 л, 299 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Белый',
        description: 'Премиум японский внедорожник, отличное состояние.',
        imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=900&h=600&fit=crop&auto=format'
    },
    {
        id: 32,
        brand: 'Lexus',
        model: 'ES',
        year: 2021,
        price: 4200000,
        mileage: 22000,
        bodyType: 'седан',
        engine: '2.5 л, 203 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Черный',
        description: 'Роскошный бизнес-седан, полная комплектация.',
        imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=900&h=600&fit=crop&auto=format'
    },
    {
        id: 33,
        brand: 'Porsche',
        model: 'Cayenne',
        year: 2022,
        price: 7200000,
        mileage: 10000,
        bodyType: 'внедорожник',
        engine: '3.0 л, 340 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Белый',
        description: 'Спортивный внедорожник премиум класса',
        imageUrl: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=900&h=600&fit=crop&auto=format'
    },
    {
        id: 34,
        brand: 'Porsche',
        model: 'Panamera',
        year: 2021,
        price: 8500000,
        mileage: 15000,
        bodyType: 'седан',
        engine: '2.9 л, 330 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Серый',
        description: 'Спортивный седан премиум класса',
        imageUrl: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=900&h=600&fit=crop&auto=format'
    },
    {
        id: 35,
        brand: 'Volvo',
        model: 'XC90',
        year: 2022,
        price: 5200000,
        mileage: 12000,
        bodyType: 'внедорожник',
        engine: '2.0 л, 320 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Черный',
        description: 'Безопасный и комфортный внедорожник.',
        imageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=900&h=600&fit=crop&auto=format'
    },
    {
        id: 36,
        brand: 'Volvo',
        model: 'S90',
        year: 2021,
        price: 3800000,
        mileage: 25000,
        bodyType: 'седан',
        engine: '2.0 л, 250 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Белый',
        description: 'Премиум седан с акцентом на безопасно',
        imageUrl: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=750&h=550&fit=crop&auto=format'
    },
    {
        id: 37,
        brand: 'Hyundai',
        model: 'Tucson',
        year: 2022,
        price: 2800000,
        mileage: 20000,
        bodyType: 'внедорожник',
        engine: '2.0 л, 150 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Серый',
        description: 'Современный корейский кро',
        imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=750&h=550&fit=crop&auto=format'
    },
    {
        id: 38,
        brand: 'Hyundai',
        model: 'Sonata',
        year: 2021,
        price: 2200000,
        mileage: 30000,
        bodyType: 'седан',
        engine: '2.0 л, 150 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Белый',
        description: 'Стильный и надеж',
        imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=750&h=550&fit=crop&auto=format'
    },
    {
        id: 39,
        brand: 'Kia',
        model: 'Sportage',
        year: 2022,
        price: 2600000,
        mileage: 18000,
        bodyType: 'внедорожник',
        engine: '2.0 л, 150 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Синий',
        description: 'Популярный корейск',
        imageUrl: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=750&h=550&fit=crop&auto=format'
    },
    {
        id: 40,
        brand: 'Kia',
        model: 'Optima',
        year: 2021,
        price: 2100000,
        mileage: 32000,
        bodyType: 'седан',
        engine: '2.0 л, 150 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Черный',
        description: 'Комфортный бизнес-седан.',
        imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=750&h=550&fit=crop&auto=format'
    },
    {
        id: 41,
        brand: 'Mazda',
        model: 'CX-5',
        year: 2022,
        price: 2900000,
        mileage: 15000,
        bodyType: 'внедорожник',
        engine: '2.5 л, 192 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Красный',
        description: 'Спортивный ',
        imageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=750&h=550&fit=crop&auto=format'
    },
    {
        id: 42,
        brand: 'Mazda',
        model: '6',
        year: 2021,
        price: 2400000,
        mileage: 28000,
        bodyType: 'седан',
        engine: '2.0 л, 150 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Белый',
        description: 'Элегантный японский седан.',
        imageUrl: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=750&h=550&fit=crop&auto=format'
    },
    {
        id: 43,
        brand: 'Nissan',
        model: 'Qashqai',
        year: 2022,
        price: 2700000,
        mileage: 16000,
        bodyType: 'внедорожник',
        engine: '2.0 л, 144 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Серый',
        description: 'Популярный компактный кроссовер.',
        imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=750&h=550&fit=crop&auto=format'
    },
    {
        id: 44,
        brand: 'Nissan',
        model: 'Altima',
        year: 2021,
        price: 2300000,
        mileage: 30000,
        bodyType: 'седан',
        engine: '2.5 л, 188 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Черный',
        description: 'Надежный японский седан.',
        imageUrl: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=750&h=550&fit=crop&auto=format'
    },
    {
        id: 45,
        brand: 'Honda',
        model: 'CR-V',
        year: 2022,
        price: 3100000,
        mileage: 14000,
        bodyType: 'внедорожник',
        engine: '2.0 л, 184 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Белый',
        description: 'Надежный японский кроссовер.',
        imageUrl: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=750&h=550&fit=crop&auto=format'
    },
    {
        id: 46,
        brand: 'Honda',
        model: 'Accord',
        year: 2021,
        price: 2500000,
        mileage: 26000,
        bodyType: 'седан',
        engine: '1.5 л, 192 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Серый',
        description: 'Описание автомобиля.',
        imageUrl: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=750&h=550&fit=crop&auto=format'
    },
    {
        id: 47,
        brand: 'Ford',
        model: 'Explorer',
        year: 2022,
        price: 4500000,
        mileage: 12000,
        bodyType: 'внедорожник',
        engine: '2.3 л, 300 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Черный',
        description: 'Просторный американский внедорожник.',
        imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=750&h=550&fit=crop&auto=format'
    },
    {
        id: 48,
        brand: 'Ford',
        model: 'Focus',
        year: 2021,
        price: 1900000,
        mileage: 35000,
        bodyType: 'хэтчбек',
        engine: '1.5 л, 150 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Синий',
        description: 'Динамичный компактный хэтчбек.',
        imageUrl: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=850&h=650&fit=crop&auto=format'
    },
    {
        id: 49,
        brand: 'Chevrolet',
        model: 'Tahoe',
        year: 2021,
        price: 5500000,
        mileage: 20000,
        bodyType: 'внедорожник',
        engine: '5.3 л, 355 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Белый',
        description: 'Большой американский внедорожник.',
        imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=850&h=650&fit=crop&auto=format'
    },
    {
        id: 50,
        brand: 'Chevrolet',
        model: 'Malibu',
        year: 2022,
        price: 2300000,
        mileage: 18000,
        bodyType: 'седан',
        engine: '1.5 л, 163 л.с.',
        transmission: 'Автомат',
        drive: 'Передний',
        color: 'Серебристый',
        description: 'Описание автомобиля.',
        imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=850&h=650&fit=crop&auto=format'
    },
    {
        id: 51,
        brand: 'Jeep',
        model: 'Grand Cherokee',
        year: 2022,
        price: 4800000,
        mileage: 10000,
        bodyType: 'внедорожник',
        engine: '3.6 л, 293 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Черный',
        description: 'Легендарный внедорожник для бездорожья.',
        imageUrl: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=850&h=650&fit=crop&auto=format'
    },
    {
        id: 52,
        brand: 'Jeep',
        model: 'Wrangler',
        year: 2021,
        price: 4200000,
        mileage: 22000,
        bodyType: 'внедорожник',
        engine: '3.6 л, 285 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Красный',
        description: 'Классический внедорожник для приключений.',
        imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=850&h=650&fit=crop&auto=format'
    },
    {
        id: 53,
        brand: 'Subaru',
        model: 'Forester',
        year: 2022,
        price: 3200000,
        mileage: 15000,
        bodyType: 'внедорожник',
        engine: '2.5 л, 182 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Синий',
        description: 'Надежный японский внедорожник с полным приводом.',
        imageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=850&h=650&fit=crop&auto=format'
    },
    {
        id: 54,
        brand: 'Subaru',
        model: 'Outback',
        year: 2021,
        price: 3000000,
        mileage: 25000,
        bodyType: 'универсал',
        engine: '2.5 л, 182 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Белый',
        description: 'Практичный универсал с полным приводом.',
        imageUrl: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=850&h=650&fit=crop&auto=format'
    },
    {
        id: 55,
        brand: 'Infiniti',
        model: 'QX60',
        year: 2022,
        price: 5200000,
        mileage: 12000,
        bodyType: 'внедорожник',
        engine: '3.5 л, 295 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Черный',
        description: 'Роскошный японский внедорожник.',
        imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=850&h=650&fit=crop&auto=format'
    },
    {
        id: 56,
        brand: 'Infiniti',
        model: 'Q50',
        year: 2021,
        price: 3800000,
        mileage: 20000,
        bodyType: 'седан',
        engine: '2.0 л, 211 л.с.',
        transmission: 'Автомат',
        drive: 'Задний',
        color: 'Серый',
        description: 'Спортивный премиум седан.',
        imageUrl: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=850&h=650&fit=crop&auto=format'
    },
    {
        id: 57,
        brand: 'Land Rover',
        model: 'Range Rover Sport',
        year: 2022,
        price: 9500000,
        mileage: 8000,
        bodyType: 'внедорожник',
        engine: '3.0 л, 360 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Белый',
        imageUrl: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=850&h=650&fit=crop&auto=format'
    },
    {
        id: 58,
        brand: 'Land Rover',
        model: 'Discovery',
        year: 2021,
        price: 6800000,
        mileage: 18000,
        bodyType: 'внедорожник',
        engine: '3.0 л, 340 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Серый',
        description: 'Описание автомобиля.',
        imageUrl: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=850&h=650&fit=crop&auto=format'
    },
    {
        id: 59,
        brand: 'Jaguar',
        model: 'F-Pace',
        year: 2022,
        price: 6200000,
        mileage: 10000,
        bodyType: 'внедорожник',
        engine: '2.0 л, 250 л.с.',
        transmission: 'Автомат',
        drive: 'Полный',
        color: 'Синий',
        description: 'Элегантный британский внедорожник.',
        imageUrl: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=850&h=650&fit=crop&auto=format'
    },
    {
        id: 60,
        brand: 'Jaguar',
        model: 'XF',
        year: 2021,
        price: 4500000,
        mileage: 22000,
        bodyType: 'седан',
        engine: '2.0 л, 250 л.с.',
        transmission: 'Автомат',
        drive: 'Задний',
        color: 'Черный',
        description: 'Роскошный британский седан.',
        imageUrl: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=950&h=700&fit=crop&auto=format'
    },
];

// Получить все автомобили
function getAllCars() {
    return carsData;
}

// Получить автомобиль по ID
function getCarById(id) {
    return carsData.find(car => car.id === parseInt(id));
}

// Получить популярные автомобили (первые 6)
function getPopularCars() {
    return carsData.slice(0, 6);
}

// Получить похожие автомобили
function getSimilarCars(currentCar, limit = 4) {
    return carsData
        .filter(car => 
            car.id !== currentCar.id && 
            (car.brand === currentCar.brand || car.bodyType === currentCar.bodyType)
        )
        .slice(0, limit);
}

// Получить уникальные марки
function getUniqueBrands() {
    return [...new Set(carsData.map(car => car.brand))].sort();
}

// Форматировать цену
function formatPrice(price) {
    return new Intl.NumberFormat('ru-RU').format(price) + ' ₽';
}

// Форматировать пробег
function formatMileage(mileage) {
    return new Intl.NumberFormat('ru-RU').format(mileage) + ' км';
}
